version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: tyrone
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
